ALTER TYPE prazo_processual_tipo ADD VALUE IF NOT EXISTS 'RESPOSTA_IMPUGNACAO';
ALTER TYPE prazo_processual_tipo ADD VALUE IF NOT EXISTS 'RESPOSTA_ESCLARECIMENTO';
ALTER TYPE prazo_processual_tipo ADD VALUE IF NOT EXISTS 'HABILITACAO';
ALTER TYPE prazo_processual_tipo ADD VALUE IF NOT EXISTS 'ANALISE_TECNICA';
ALTER TYPE prazo_processual_tipo ADD VALUE IF NOT EXISTS 'CORRECAO';
ALTER TYPE prazo_processual_tipo ADD VALUE IF NOT EXISTS 'AUTORIZACAO';
