INSERT INTO "parametros_sistema" (
  "categoria",
  "chave",
  "valor",
  "valor_json",
  "tipo_dado",
  "descricao",
  "valor_padrao",
  "requer_reinicio",
  "versao",
  "ativo",
  "criado_em",
  "atualizado_em"
)
VALUES
  ('INSTITUCIONAL', 'INSTITUCIONAL.NOME_ORGAO', '"Prefeitura Municipal de Teixeira de Freitas"', '"Prefeitura Municipal de Teixeira de Freitas"'::jsonb, 'string', 'Nome oficial do órgão.', '"Prefeitura Municipal de Teixeira de Freitas"'::jsonb, false, 1, true, now(), now()),
  ('INSTITUCIONAL', 'INSTITUCIONAL.SIGLA_ORGAO', '"PMTF"', '"PMTF"'::jsonb, 'string', 'Sigla oficial do órgão.', '"PMTF"'::jsonb, false, 1, true, now(), now()),
  ('INSTITUCIONAL', 'INSTITUCIONAL.CNPJ_ORGAO', '"00000000000000"', '"00000000000000"'::jsonb, 'string', 'CNPJ institucional (somente números).', '"00000000000000"'::jsonb, false, 1, true, now(), now()),
  ('INSTITUCIONAL', 'INSTITUCIONAL.ENDERECO', '{"logradouro":"Av. Exemplo","numero":"100","complemento":"","bairro":"Centro","municipio":"Teixeira de Freitas","uf":"BA","cep":"45985-000"}', '{"logradouro":"Av. Exemplo","numero":"100","complemento":"","bairro":"Centro","municipio":"Teixeira de Freitas","uf":"BA","cep":"45985-000"}'::jsonb, 'object', 'Endereço oficial do órgão.', '{"logradouro":"Av. Exemplo","numero":"100","complemento":"","bairro":"Centro","municipio":"Teixeira de Freitas","uf":"BA","cep":"45985-000"}'::jsonb, false, 1, true, now(), now()),
  ('INSTITUCIONAL', 'INSTITUCIONAL.EMAIL_OFICIAL', '"licitacao@teixeiradefreitas.ba.gov.br"', '"licitacao@teixeiradefreitas.ba.gov.br"'::jsonb, 'string', 'E-mail oficial para contato.', '"licitacao@teixeiradefreitas.ba.gov.br"'::jsonb, false, 1, true, now(), now()),
  ('INSTITUCIONAL', 'INSTITUCIONAL.TELEFONE_OFICIAL', '"(73) 0000-0000"', '"(73) 0000-0000"'::jsonb, 'string', 'Telefone oficial para contato.', '"(73) 0000-0000"'::jsonb, false, 1, true, now(), now()),
  ('COMPORTAMENTO', 'VISUAL.LOGO_URL', '"/assets/logo-prefeitura.png"', '"/assets/logo-prefeitura.png"'::jsonb, 'string', 'Logo institucional exibida no sistema.', '"/assets/logo-prefeitura.png"'::jsonb, false, 1, true, now(), now()),
  ('COMPORTAMENTO', 'VISUAL.COR_PRIMARIA', '"#4169E1"', '"#4169E1"'::jsonb, 'string', 'Cor primária do tema institucional.', '"#4169E1"'::jsonb, false, 1, true, now(), now()),
  ('COMPORTAMENTO', 'VISUAL.COR_SECUNDARIA', '"#0F1A6D"', '"#0F1A6D"'::jsonb, 'string', 'Cor secundária do tema institucional.', '"#0F1A6D"'::jsonb, false, 1, true, now(), now()),
  ('COMPORTAMENTO', 'SISTEMA.RODAPE', '"Sistema oficial de gestão licitatória - SIREL Beta 2.0"', '"Sistema oficial de gestão licitatória - SIREL Beta 2.0"'::jsonb, 'string', 'Texto padrão do rodapé do sistema.', '"Sistema oficial de gestão licitatória - SIREL Beta 2.0"'::jsonb, false, 1, true, now(), now()),
  ('REGRAS', 'LIMITES.DISPENSA.INCISO_I', '119217.89', '119217.89'::jsonb, 'number', 'Limite legal para dispensa - Inciso I (obras e serviços de engenharia).', '119217.89'::jsonb, false, 1, true, now(), now()),
  ('REGRAS', 'LIMITES.DISPENSA.INCISO_II', '59908.94', '59908.94'::jsonb, 'number', 'Limite legal para dispensa - Inciso II (outros serviços e compras).', '59908.94'::jsonb, false, 1, true, now(), now()),
  ('REGRAS', 'PRAZOS.DISPENSA.PUBLICACAO_RESUMO_DIAS_UTEIS', '5', '5'::jsonb, 'number', 'Contador automático de prazo para publicação do resumo da dispensa.', '5'::jsonb, false, 1, true, now(), now()),
  ('REGRAS', 'PRAZOS.PREGAO.RECEBIMENTO_PROPOSTAS_DIAS_UTEIS', '8', '8'::jsonb, 'number', 'Contador automático de prazo para recebimento de propostas no pregão.', '8'::jsonb, false, 1, true, now(), now()),
  ('REGRAS', 'PRAZOS.CONCORRENCIA.OBRAS_DIAS_UTEIS', '45', '45'::jsonb, 'number', 'Contador automático de prazo para concorrência de obras.', '45'::jsonb, false, 1, true, now(), now()),
  ('REGRAS', 'PRAZOS.CONCORRENCIA.SERVICOS_DIAS_UTEIS', '30', '30'::jsonb, 'number', 'Contador automático de prazo para concorrência de serviços.', '30'::jsonb, false, 1, true, now(), now()),
  ('REGRAS', 'PRAZOS.RECURSOS.ADMINISTRATIVOS_DIAS_UTEIS', '3', '3'::jsonb, 'number', 'Prazo padrão de recursos administrativos.', '3'::jsonb, false, 1, true, now(), now()),
  ('COMPORTAMENTO', 'UPLOAD.TAMANHO_MAXIMO_MB', '100', '100'::jsonb, 'number', 'Tamanho máximo de upload por arquivo (MB).', '100'::jsonb, false, 1, true, now(), now()),
  ('COMPORTAMENTO', 'NOTIFICACOES.ALERTA_PRAZO_DIAS', '[7,3,1]', '[7,3,1]'::jsonb, 'array', 'Dias de antecedência para alertas de prazo.', '[7,3,1]'::jsonb, false, 1, true, now(), now()),
  ('COMPORTAMENTO', 'SESSAO.TEMPO_INATIVIDADE_MINUTOS', '30', '30'::jsonb, 'number', 'Tempo máximo de inatividade da sessão em minutos.', '30'::jsonb, false, 1, true, now(), now()),
  ('INTEGRACAO', 'INTEGRACAO.BLL.HABILITADO', 'true', 'true'::jsonb, 'boolean', 'Habilita integração e lembretes de publicação BLL.', 'true'::jsonb, false, 1, true, now(), now()),
  ('INTEGRACAO', 'INTEGRACAO.BLL.FORMATO_EXPORTACAO', '"JSON"', '"JSON"'::jsonb, 'string', 'Formato padrão de exportação para integração BLL.', '"JSON"'::jsonb, false, 1, true, now(), now()),
  ('INTEGRACAO', 'INTEGRACAO.PNCP.HABILITADO', 'false', 'false'::jsonb, 'boolean', 'Habilita integração PNCP (preparatório).', 'false'::jsonb, false, 1, true, now(), now())
ON CONFLICT ("chave") DO UPDATE
SET
  "categoria" = EXCLUDED."categoria",
  "valor" = EXCLUDED."valor",
  "valor_json" = EXCLUDED."valor_json",
  "tipo_dado" = EXCLUDED."tipo_dado",
  "descricao" = EXCLUDED."descricao",
  "valor_padrao" = EXCLUDED."valor_padrao",
  "requer_reinicio" = EXCLUDED."requer_reinicio",
  "ativo" = true,
  "atualizado_em" = now();
