const LEGACY_CONDUTOR_NAME_PAIRS = [
  ["1", "MAGDA DE SELES GUIMARÃES"],
  ["2", "RANNA SOUZA BARROSO"],
  ["5", "JONATAS DA SILVA SOUSA"],
  ["7", "SÉRGIO CARNEIRO CAVALCANTI DE AZEVEDO"],
  ["9", "ARNALDO ROSA DOS SANTOS FILHO"],
  ["10", "ISAQUE SILVA DOS SANTOS"],
  ["27", "ISLA LIMA SILVA"],
  ["28", "VICTOR KINIDEL DETHLING"],
  ["35", "FERNANDO ANDERSON DETHLING"],
] as const;

const LEGACY_SECRETARIA_NAME_PAIRS = [
  ["ADMINISTRAÇÃO", "SECRETARIA DE ADMINISTRAÇÃO"],
  ["ADMINISTRAÇÃO E DEMAIS", "SECRETARIA DE ADMINISTRAÇÃO"],
  ["ADMINISTRAÇÃO E PLANEJAMENTO", "SECRETARIA DE ADMINISTRAÇÃO"],
  [
    "AGRICULTURA E ABASTECIMENTO",
    "SECRETARIA DE AGRICULTURA PECUÁRIA E ABASTECIMENTO",
  ],
  [
    "AGRICULTURA E PECUARIA",
    "SECRETARIA DE AGRICULTURA PECUÁRIA E ABASTECIMENTO",
  ],
  [
    "AGRICULTURA, PECUÁRIA E ABASTECIMENTO",
    "SECRETARIA DE AGRICULTURA PECUÁRIA E ABASTECIMENTO",
  ],
  ["ASSISTÊNCIA SOCIAL", "SECRETARIA DE PROMOÇÃO SOCIAL"],
  ["CULTURA E TURISMO", "SECRETARIA DE CULTURA E TURISMO"],
  [
    "DESENVOLVIMENTO ECONOMICO",
    "SECRETARIA DE DESENVOLVIMENTO ECONÔMICO, CIÊNCIA E TECNOLOGIA",
  ],
  [
    "DESENVOLVIMENTO ECONÔMICO",
    "SECRETARIA DE DESENVOLVIMENTO ECONÔMICO, CIÊNCIA E TECNOLOGIA",
  ],
  ["EDUCAÇÃO", "SECRETARIA DE EDUCAÇÃO"],
  ["EDUCAÇÃO E CULTURA", "SECRETARIA DE EDUCAÇÃO"],
  ["ESPORTE E LAZER", "SECRETARIA DE ESPORTE E LAZER"],
  ["FINANÇAS", "SECRETARIA DE FINANÇAS"],
  [
    "FUNDO MUN. DE EDUCAÇÃO DE TEIXEIRA DE FREITAS",
    "SECRETARIA DE EDUCAÇÃO",
  ],
  [
    "FUNDO MUNICIPAL DE ASSISTÊNCIA SOCIAL",
    "SECRETARIA DE PROMOÇÃO SOCIAL",
  ],
  [
    "FUNDO MUNICIPAL DE SAÚDE DE TEIXEIRA DE FREITAS",
    "SECRETARIA DE SAÚDE",
  ],
  ["GABINETE DO PREFEITO", "GABINETE DO PREFEITO"],
  ["HABITAÇÃO", "SECRETARIA DE HABITAÇÃO"],
  [
    "INFRAESTRUTURA",
    "SECRETARIA DE INFRAESTRUTURA E SERVIÇOS URBANOS",
  ],
  [
    "INFRAESTRUTURA E SERVIÇOS URBANOS",
    "SECRETARIA DE INFRAESTRUTURA E SERVIÇOS URBANOS",
  ],
  ["MEIO AMBIENTE", "SECRETARIA DE MEIO AMBIENTE"],
  [
    "PREFEITURA MUNICIPAL DE TEIXEIRA DE FREITAS",
    "SECRETARIA DE ADMINISTRAÇÃO",
  ],
  [
    "PROJETOS ESTRATÉGICOS E GERENCIAMENTO DE CONVÊNIOS",
    "SECRETARIA DE PROJETOS ESTRATÉGICOS E GERENCIAMENTO DE CONVÊNIOS",
  ],
  ["PROMOÇÃO SOCIAL E CULTURA", "SECRETARIA DE PROMOÇÃO SOCIAL"],
  ["SAÚDE", "SECRETARIA DE SAÚDE"],
  ["SEGURANÇA", "SECRETARIA DE SEGURANÇA E TRANSPORTE"],
  ["SEGURANÇA E CIDADANIA", "SECRETARIA DE SEGURANÇA E TRANSPORTE"],
  ["SEGURANÇA E TRANSPORTE", "SECRETARIA DE SEGURANÇA E TRANSPORTE"],
  ["XXX", "SECRETARIA DE ADMINISTRAÇÃO"],
] as const;

function normalizeLegacyMappingKey(value: string) {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .toUpperCase();
}

export const LEGACY_CONDUTOR_NAME_MAP = new Map<string, string>(
  LEGACY_CONDUTOR_NAME_PAIRS.map(([source, target]) => [
    normalizeLegacyMappingKey(source),
    target,
  ]),
);

export const LEGACY_SECRETARIA_NAME_MAP = new Map<string, string>(
  LEGACY_SECRETARIA_NAME_PAIRS.map(([source, target]) => [
    normalizeLegacyMappingKey(source),
    target,
  ]),
);

export function mapLegacyCondutorName(value: string | null | undefined) {
  const text = value?.trim();
  if (!text) return null;
  return LEGACY_CONDUTOR_NAME_MAP.get(normalizeLegacyMappingKey(text)) ?? text;
}

export function mapLegacySecretariaName(value: string | null | undefined) {
  const text = value?.trim();
  if (!text) return null;
  return LEGACY_SECRETARIA_NAME_MAP.get(normalizeLegacyMappingKey(text)) ?? text;
}
